[versions]
# conventions
mapstruct = "1.5.5.Final"
mcveConventions = "0.1.0-SNAPSHOT"

[libraries]
# conventions
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

[plugins]
#conventions
mcve-spring-boot-conventions = { id = "mcve-spring-conventions", version.ref = "mcveConventions" }
